environment: dev

echo:
  replicaCount: 2

whoami:
  replicaCount: 1

ingress:
  host: hello-dev.local

config:
  appName: apps-dev
  logLevel: debug
  welcomeMessage: Hello from the development environment

secret:
  existingSecret: apps-dev-secret
