apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: course-bootstrap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amerinoo/kubernetes-from-zero.git
    targetRevision: main
    path: classes/13-applicationsets-matrix
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
