apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: {{ .Values.echo.replicaCount }}
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: "{{ .Values.echo.image.repository }}:{{ .Values.echo.image.tag }}"
          ports:
            - containerPort: 80
