apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amerinoo/kubernetes-from-zero.git
    targetRevision: main
    path: classes/10-helm-secrets/apps
    helm:
      releaseName: apps-dev
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
